### ISSUE TITLE
bot execution problem

### ISSUE THREAD

**Issue by abssolum** [chopbk/binance-leaderboard-bot#1]
hi

i am trying to use your telegram bot. When I run the node index.js command the script stops at "getMe" . The telegram channel is detected but nothing happens. I have no error. Do you have an idea of ​​the problem? 

Thanks

**Comment by chopbk** [comment]
did you add telegram bot token to .env file

**Comment by abssolum** [comment]
yes

**Comment by abssolum** [comment]
here is the message i get: 
node index.js 
2022-10-05 21:01:27.657 [debug]: [mongoLoader] connect to mongodb://127.0.0.1:27017/creationAirdrop?authSource=creationAirdrop 
Connect to mongodb://127.0.0.1:27017/creationAirdrop?authSource=creationAirdrop success
2022-10-05 21:01:28.220 [debug]: getMe {"id":xxxxxxxxx,"is_bot":true,"first_name":"xxxxxxxxx","username":"xxxxxxxxxxxxxxxxx_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false} 
is there another configuration file other than .env to complete? should we launch another command other than node index.js? Thanks

**Comment by chopbk** [comment]
```
TOKEN=<telegram bot token>
MONGODB_USERNAME=<username>
MONGODB_PASS=<[password]>
MONGO_URI=mongodb+srv://xxxx/binance_leaderboard
NTBA_FIX_319=true
```
Just use some env field. if telegram bot starts successfully, u can dm that bot and /start to start interacting with bot. Some commands now can use is 
/p - /position <uid> : get current position of uid
/i <uid> : get performance info of uid
/s <uid> get some statistics of uid from futuresheros
